[project]
name = "freshdesk-mcp-support"
version = "1.0.6"
description = "An MCP server for Freshdesk"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "build>=1.2.2.post1",
    "httpx==0.28.1",
    "mcp[cli]>=1.3.0",
    "pydantic>=2.10.6",
]

[[project.authors]]
name = "Kalidass Mani"
email = "kalidass.mani@freshworks.com"

[build-system]
requires = [ "hatchling", "setuptools", "wheel"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/freshdesk_mcp"]

[project.scripts]
freshdesk-mcp-support = "freshdesk_mcp.server:main"
